--[[[ BZ_BOARD_01

DROP TABLE BZ_BOARD;

--]]]
--[[[ BZ_BOARD_02

CREATE TABLE BZ_BOARD(
N INT(10) AUTO_INCREMENT
, TITLE VARCHAR(1000) 
, TXT VARCHAR(1000)
, EM VARCHAR(1000)
, FILE_NM_1 VARCHAR(1000)
, FILE_ID_1 VARCHAR(1000)
, FILE_NM_2 VARCHAR(1000)
, FILE_ID_2 VARCHAR(1000)
, RG_ID VARCHAR(1000)
, RG_IP VARCHAR(1000)
, RG_DTM VARCHAR(1000)
, MDF_ID VARCHAR(1000)
, MDF_IP VARCHAR(1000)
, MDF_DTM VARCHAR(1000)
, DEL_Y VARCHAR(1000)
, CONSTRAINT PK_BZ_BOARD PRIMARY KEY(N)
);


 

--]]]

--[[[ BZ_BOARD_03
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES('TITLE 1','TXT 1', 'EM 1');
--]]]

--[[[ BZ_BOARD_04
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES('TITLE 2','TXT 2', 'EM 2');
--]]]

--[[[ BZ_BOARD_05
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES('TITLE 3','TXT 3', 'EM 3');
--]]]


--[[[ FW_CONTROLLER_01


drop table FW_CONTROLLER;

--]]]
--[[[ FW_CONTROLLER_02

CREATE TABLE FW_CONTROLLER(
FW_KEY VARCHAR(1000)
, CLASS_NAME VARCHAR(1000)
, METHOD_NAME VARCHAR(1000)
);

--]]]


--[[[ FW_CONTROLLER_I_01
INSERT INTO FW_CONTROLLER VALUES('callList','com.biz.board.Board','callList');
--]]]

--[[[ FW_CONTROLLER_I_02
INSERT INTO FW_CONTROLLER VALUES('callWrite','com.biz.board.Board','callWrite');
--]]]

--[[[ FW_CONTROLLER_I_03
INSERT INTO FW_CONTROLLER VALUES('exeWrite','com.biz.board.Board','exeWrite');
--]]]

--[[[ FW_CONTROLLER_I_04
INSERT INTO FW_CONTROLLER VALUES('exeLogin','com.biz.login.Login','exeLogin');
--]]]

--[[[ FW_CONTROLLER_I_05
INSERT INTO FW_CONTROLLER VALUES('callLogin','com.biz.login.Login','callLogin');
--]]]
