cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db

ALTER TABLE FW_CONTROLLER ADD SESSION_CHECK_YN;
ALTER TABLE FW_CONTROLLER ADD AUTH;

UPDATE FW_CONTROLLER SET SESSION_CHECK_YN = 'N', AUTH = '' WHERE KEY IN ('login','loginView');
UPDATE FW_CONTROLLER SET SESSION_CHECK_YN = 'Y', AUTH = '' WHERE KEY = 'emp00110';
UPDATE FW_CONTROLLER SET SESSION_CHECK_YN = 'Y', AUTH = 'A0' WHERE KEY = 'emp00120';

UPDATE FW_SQL SET SQL = 'SELECT
KEY
, CLASS_NAME
, METHOD_NAME
, SESSION_CHECK_YN
, AUTH
FROM FW_CONTROLLER
WHERE KEY = [KEY]
'
WHERE KEY = 'MASTERCONTROLLERD_01';

DROP TABLE BZ_ID;

CREATE TABLE BZ_ID (
ID PRIMARY KEY
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM
);


INSERT INTO BZ_ID values (
'id_A0'
, 'abcd1111'
, 'A0'
, '0'
, ''
);

INSERT INTO BZ_ID values (
'id_U0'
, 'abcd1111'
, 'U0'
, '0'
, ''
);

DELETE FROM FW_SQL WHERE KEY IN ('LOGIND_01','LOGIND_02','LOGIND_03');

INSERT INTO FW_SQL values (
'LOGIND_01'
, 'SELECT 
ID
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM 
FROM 
BZ_ID
WHERE ID = [ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_02'
, 'UPDATE BZ_ID
SET FAIL_CNT = FAIL_CNT + 1
WHERE ID = [ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_03'
,'UPDATE BZ_ID
SET FAIL_CNT = 0
, LAST_LOGIN_DTM = [LAST_LOGIN_DTM]
WHERE ID = [ID]
');