cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db

DROP TABLE EMP ;

CREATE TABLE EMP (
EMP_N PRIMARY KEY
, EMP_NM
, HP_N
, DEPT_N
);

INSERT INTO EMP VALUES ('N0001','ABC','','D01');
INSERT INTO EMP VALUES ('N0002','ZZZ','','D01');
INSERT INTO EMP VALUES ('N0003','ABC','','D02');



DROP TABLE FW_SQL;

CREATE TABLE FW_SQL (
KEY PRIMARY KEY
, SQL
);


INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_01', 'SELECT EMP_N, EMP_NM, DEPT_NO FROM EMP WHERE EMP_NM = [EMP_NM] ORDER BY EMP_N');

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_02_1', 'INSERT INTO EMP(KEY,SQL) VALUES ([KEY],[SQL])');

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_02_2', 'UPDATE FW_SQL SET SQL = [SQL] WHERE KEY =[KEY]');

