cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db



DROP TABLE FW_SQL;

CREATE TABLE FW_SQL (
KEY PRIMARY KEY
, SQL
);

DROP TABLE EMP ;

CREATE TABLE EMP (
EMP_NO PRIMARY KEY
, EMP_NM
, HP_N
, DEPT_NO
);


INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_01', 'SELECT * FROM EMP WHERE KEY = [KEY]');

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_02_1', 'INSERT INTO FW_SQL(KEY,SQL) VALUES ([KEY],[SQL])');

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_02_2', 'UPDATE FW_SQL SET SQL = [SQL] WHERE KEY =[KEY]');

