DROP TABLE BZ_BOARD;

CREATE TABLE BZ_BOARD(
N INTEGER PRIMARY KEY AUTOINCREMENT
, TITLE
, TXT
, EM
, FILE_NM_1
, FILE_ID_1
, FILE_NM_2
, FILE_ID_2
, RG_ID
, RG_IP
, RG_DTM
, MDF_ID
, MDF_IP
, MDF_DTM
, DEL_Y
);

INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES ('제목 1 B ', '내용1',null);
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES ('제목 2 A ', null,null);
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES ('제목 3 A ', '내용3',null);
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES ('제목 4 B ', '내용4',null);
INSERT INTO BZ_BOARD (TITLE, TXT, EM) VALUES ('제목 5 B ', '내용5',null);