cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db


DROP TABLE FW_CONTROLLER;

DROP TABLE FW_VIEW;

CREATE TABLE FW_SQL (
KEY PRIMARY KEY
, SQL
);

CREATE TABLE FW_CONTROLLER (
KEY PRIMARY KEY
, CLASS_NAME
, METHOD_NAME
);

CREATE TABLE FW_VIEW (
KEY PRIMARY KEY
, JSP
);

INSERT INTO FW_SQL VALUES (
'MASTERCONTROLLERD_01'
, 'SELECT
KEY
, CLASS_NAME
, METHOD_NAME
FROM FW_CONTROLLER
WHERE KEY = [KEY]'
);

INSERT INTO FW_SQL VALUES (
'MASTERCONTROLLERD_02'
, 'SELECT
KEY
, JSP
FROM FW_VIEW
WHERE KEY = [KEY]'
);



INSERT INTO FW_CONTROLLER VALUES ('mng00110','com.biz.mng001.Mng001','mng00110');
INSERT INTO FW_CONTROLLER VALUES ('mng00111','com.biz.mng001.Mng001','mng00111');

INSERT INTO FW_VIEW VALUES ('mng00110','/WEB-INF/classes/com/biz/mng001/jsp/mng00110.jsp');

INSERT INTO FW_CONTROLLER VALUES ('login','com.biz.login.Login','login');
INSERT INTO FW_CONTROLLER VALUES ('loginView','com.biz.login.Login','loginView');
INSERT INTO FW_CONTROLLER VALUES ('logout','com.biz.login.Login','logout');

INSERT INTO FW_VIEW VALUES ('loginView','/WEB-INF/classes/com/biz/login/jsp/loginView.jsp');



INSERT INTO FW_SQL VALUES ('MNG001D_01','SELECT KEY
, SQL
FROM FW_SQL
WHERE KEY = [KEY]
');

INSERT INTO FW_SQL VALUES ('MNG001D_02','UPDATE FW_SQL
SET SQL = [SQL]
WHERE KEY = [KEY]
');

INSERT INTO FW_SQL VALUES ('MNG001D_03','INSERT INTO FW_SQL (
KEY
, SQL
) VALUES (
[KEY]
, [SQL]
)
');

