cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db

DROP TABLE FW_FILE_UPLOAD; 

CREATE TABLE FW_FILE_UPLOAD (
FILE_ID primary KEY
, SIZE
, CONTENT_TYPE
, FILE_NAME
, FILE_URL
, RG_ID
, RG_DTM
);


DROP TABLE FW_FILE_DOWNLOAD; 

CREATE TABLE FW_FILE_DOWNLOAD (
FILE_ID
, ID
, ST_DTM
, ED_DTM
);

DELETE FROM FW_SQL WHERE KEY = 'UPLOADFILEB_01';
insert into FW_SQL (KEY, SQL) VALUES ('UPLOADFILEB_01', 'INSERT INTO FW_FILE_UPLOAD (
FILE_ID
, SIZE
, CONTENT_TYPE
, FILE_NAME
, FILE_URL
, RG_ID
, RG_DTM
) VALUES (
[UPLOADFILEB.FILE_ID]
, [UPLOADFILEB.SIZE]
, [UPLOADFILEB.CONTENT_TYPE]
, [UPLOADFILEB.FILE_NAME]
, [UPLOADFILEB.FILE_URL]
, [SESSIONB__ID]
, [SYSDTM__DTM]
)
');

DELETE FROM FW_SQL WHERE KEY = 'MASTERCONTROLLERMULTIPART_01';
insert into FW_SQL (KEY, SQL) VALUES ('MASTERCONTROLLERMULTIPART_01', 'SELECT * FROM FW_FILE_UPLOAD WHERE FILE_ID = [FILE_ID]');

DELETE FROM FW_SQL WHERE KEY = 'MASTERCONTROLLERMULTIPART_02';
insert into FW_SQL (KEY, SQL) VALUES ('MASTERCONTROLLERMULTIPART_02', 'INSERT INTO FW_FILE_DOWNLOAD (
FILE_ID
, ID
, ST_DTM
, ED_DTM
) values (
[FILE_ID]
, [SESSIONB__ID]
, [ST_DTM]
, [SYSDTM__DTM]
)'
);

ALTER TABLE EMP ADD FILE_ID;

UPDATE FW_SQL SET SQL ='SELECT * FROM EMP WHERE EMP_NM LIKE [EMP_NM]||'''%''' ORDER BY EMP_N' WHERE KEY = 'EMP001D_01';
UPDATE FW_SQL SET SQL ='UPDATE EMP 
SET HP_N = [HP_N] 
, FILE_ID = [FILE_ID]
WHERE EMP_N =[EMP_N]' WHERE KEY = 'EMP001D_02';




