--[[[ BZ_BOARD_01

DROP TABLE BZ_BOARD;

--]]]
--[[[ BZ_BOARD_02

CREATE TABLE BZ_BOARD(
N INTEGER PRIMARY KEY AUTOINCREMENT
, TITLE
, TXT
, EM
, FILE_NM_1
, FILE_ID_1
, FILE_NM_2
, FILE_ID_2
, RG_ID
, RG_IP
, RG_DTM
, MDF_ID
, MDF_IP
, MDF_DTM
, DEL_Y
);

--]]]

--[[[ BZ_BOARD_I_01
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T1","AAAA","");
--]]]

--[[[ BZ_BOARD_I_02
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T2","ABCD","");
--]]]

--[[[ BZ_BOARD_I_03
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T3","AAAA","");
--]]]

--[[[ BZ_BOARD_I_04
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T4","ABCD","");
--]]]

--[[[ BZ_BOARD_I_05
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T5","AAAA","");
--]]]
