--[[[ BZ_BOARD_01

DROP TABLE BZ_BOARD;

--]]]
--[[[ BZ_BOARD_02

CREATE TABLE BZ_BOARD(
N INT(10) AUTO_INCREMENT
, TITLE VARCHAR(1000) 
, TXT VARCHAR(1000)
, EM VARCHAR(1000)
, FILE_NM_1 VARCHAR(1000)
, FILE_ID_1 VARCHAR(1000)
, FILE_NM_2 VARCHAR(1000)
, FILE_ID_2 VARCHAR(1000)
, RG_ID VARCHAR(1000)
, RG_IP VARCHAR(1000)
, RG_DTM VARCHAR(1000)
, MDF_ID VARCHAR(1000)
, MDF_IP VARCHAR(1000)
, MDF_DTM VARCHAR(1000)
, DEL_Y VARCHAR(1000)
, CONSTRAINT PK_BZ_BOARD PRIMARY KEY(N) 


);

--]]]

--[[[ BZ_BOARD_I_01
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T1","AAAA","");
--]]]

--[[[ BZ_BOARD_I_02
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T2","ABCD","");
--]]]

--[[[ BZ_BOARD_I_03
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T3","AAAA","");
--]]]

--[[[ BZ_BOARD_I_04
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T4","ABCD","");
--]]]

--[[[ BZ_BOARD_I_05
INSERT INTO BZ_BOARD(TITLE,TXT,EM) VALUES ("T5","AAAA","");
--]]]
