cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db



DROP TABLE FW_SQL;

CREATE TABLE FW_SQL (
KEY PRIMARY KEY
, SQL
);

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_01', 'SELECT * FROM FW_SQL');

INSERT INTO FW_SQL VALUES ('SQLRUNNER_TEST_02', 'INSERT INTO FW_SQL(KEY,SQL) VALUES ([KEY],[SQL])');


