cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db


ALTER TABLE FW_CONTROLLER ADD SESSION_CHECK_YN;
ALTER TABLE FW_CONTROLLER ADD AUTH;

UPDATE FW_SQL SET SQL = 'SELECT
KEY
, CLASS_NAME
, METHOD_NAME
, SESSION_CHECK_YN
, AUTH
FROM FW_CONTROLLER
WHERE KEY = [KEY]
'
WHERE KEY = 'MASTERCONTROLLERD_01';


UPDATE FW_CONTROLLER SET SESSION_CHECK_YN = 'Y';
UPDATE FW_CONTROLLER SET SESSION_CHECK_YN = '' WHERE KEY IN ('loginView','login');

UPDATE FW_CONTROLLER SET AUTH = '';
UPDATE FW_CONTROLLER SET AUTH = 'A0,U0' WHERE KEY = 'mng00110';
UPDATE FW_CONTROLLER SET AUTH = 'A0' WHERE KEY = 'mng00111';




CREATE TABLE BZ_ID (
ID PRIMARY KEY
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM
);


INSERT INTO BZ_ID values (
'idA0'
, 'abcd1111'
, 'A0'
, '0'
, ''
);

INSERT INTO BZ_ID values (
'idU0'
, 'abcd1111'
, 'U0'
, '0'
, ''
);


INSERT INTO FW_SQL values (
'LOGIND_01'
, 'SELECT 
ID
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM 
FROM 
BZ_ID
WHERE ID = [ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_02'
, 'UPDATE BZ_ID
SET FAIL_CNT = FAIL_CNT + 1
WHERE ID = [ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_03'
,'UPDATE BZ_ID
SET FAIL_CNT = 0
, LAST_LOGIN_DTM = [LAST_LOGIN_DTM]
WHERE ID = [ID]
');