cd C:\public\lib\sqlite
sqlite3 C:\public\code5\doc\code5.db


DROP TABLE EMP ;
CREATE TABLE EMP (
EMP_N PRIMARY KEY
, EMP_NM
, HP_N
, DEPT_N
, FILE_ID);
INSERT INTO EMP VALUES('N0001','ABC','','D01','');
INSERT INTO EMP VALUES('N0002','ZZZ','6b0e62cc4ad4508b108540aba547afa8','D01','');
INSERT INTO EMP VALUES('N0003','ABC','55afea71894c57aa58405a112ab7532d','D02','');
DROP TABLE FW_SQL;
CREATE TABLE FW_SQL (
KEY PRIMARY KEY
, SQL
, TIME_OUT);
INSERT INTO FW_SQL VALUES('SQLRUNNER_TEST_01','SELECT EMP_N, EMP_NM, DEPT_N FROM EMP WHERE EMP_NM = [EMP_NM] ORDER BY EMP_N',NULL);
INSERT INTO FW_SQL VALUES('SQLRUNNER_TEST_02','UPDATE EMP SET HP_N = [HP_N] WHERE EMP_N =[EMP_N]',NULL);
INSERT INTO FW_SQL VALUES('DATACRYPT_01','SELECT * FROM FW_SRT WHERE OPT = [OPT]',NULL);
INSERT INTO FW_SQL VALUES('MASTERCONTROLLERD_01','SELECT * FROM FW_CONTROLLER WHERE KEY = [KEY]',NULL);
INSERT INTO FW_SQL VALUES('MASTERCONTROLLERD_02','SELECT * FROM FW_VIEW WHERE KEY = [KEY]',NULL);
INSERT INTO FW_SQL VALUES('LOGIND_01',replace('SELECT \nID\n, PIN\n, AUTH\n, FAIL_CNT\n, LAST_LOGIN_DTM \nFROM \nBZ_ID\nWHERE ID = [ID] \n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('LOGIND_02',replace('UPDATE BZ_ID\nSET FAIL_CNT = FAIL_CNT + 1\nWHERE ID = [ID] \n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('LOGIND_03',replace('UPDATE BZ_ID\nSET FAIL_CNT = 0\n, LAST_LOGIN_DTM = [LAST_LOGIN_DTM]\nWHERE ID = [ID]\n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('EMP001D_01','SELECT AA.*, BB.FILE_NAME FROM EMP AA LEFT OUTER JOIN FW_UPLOAD_FILE BB ON AA.FILE_ID = BB.FILE_ID WHERE EMP_NM LIKE [EMP_NM]||''%'' ORDER BY EMP_N',NULL);
INSERT INTO FW_SQL VALUES('EMP001D_02',replace('UPDATE EMP \nSET HP_N = [HP_N] \n, FILE_ID = [FILE_ID]\nWHERE EMP_N =[EMP_N]','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('MASTERCONTROLLERMULTIPART_02',replace('INSERT INTO FW_FILE_DOWNLOAD (\nFILE_ID\n, ID\n, ST_DTM\n, ED_DTM\n) values (\n[FILE_ID]\n, [SESSIONB__ID]\n, [ST_DTM]\n, [SYSDTM__DTM]\n)','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('FILEDOWNLOAD_01',replace('INSERT INTO FW_FILE_DOWNLOAD (\nFILE_ID\n, ID\n, ST_DTM\n, ED_DTM\n) values (\n[FILE_ID]\n, [SESSIONB__ID]\n, [ST_DTM]\n, [ED_DTM]\n)','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('UPLOADFILEB_01',replace('INSERT INTO FW_UPLOAD_FILE (\nFILE_ID\n, SIZE\n, CONTENT_TYPE\n, FILE_NAME\n, FILE_URL\n, RG_ID\n, RG_DTM\n) VALUES (\n[UPLOADFILEB.FILE_ID]\n, [UPLOADFILEB.SIZE]\n, [UPLOADFILEB.CONTENT_TYPE]\n, [UPLOADFILEB.FILE_NAME]\n, [UPLOADFILEB.FILE_URL]\n, [SESSIONB__ID]\n, [SYSDTM__DTM]\n)\n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('UPLOADFILEB_02','SELECT * FROM FW_UPLOAD_FILE WHERE FILE_ID = [FILE_ID]',NULL);
INSERT INTO FW_SQL VALUES('UPLOADFILEB_03',replace('UPDATE FW_UPLOAD_FILE\nSET DEL_Y =''Y''\n, DEL_ID = [SESSIONB__ID]\n, DEL_DTM = [SYSDTM__DTM]  \nWHERE FILE_ID = [FILE_ID]','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('MASTERCONTROLLERMULTIPART_01','SELECT * FROM FW_UPLOAD_FILE WHERE FILE_ID = [FILE_ID]',NULL);
INSERT INTO FW_SQL VALUES('DOWNLOADFILE_01',replace('INSERT INTO FW_DOWNLOAD_FILE (\nFILE_ID\n, ID\n, DTM\n) values (\n[FILE_ID]\n, [SESSIONB__ID]\n, [DTM]\n)','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('SQLRUNNER_TEST_04',replace('[~ P1 ^ IS_NOT_NULL ^ AND [P1] = [P1] ~]\n[~ P2 ^ IS_NULL ^ AND 2 = 2 ~]\n[~ P3 ^ Y ^ AND ''Y'' = [P3] ~]\n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('SQLRUNNER_TEST_03',replace('SELECT\n[HP_N] HP_N\n, [HP_N] DEC__HP_N2__PRN_HP_N\n, [ENC__HP_N] HP_N3\n, [SYSDTM.DTM] DTM1\n, [SYSDTM.DTM] DTM2__PRN_DTM\n, [SESSIONB.ID] SESSION_ID\n, [SESSIONB.IP] SESSION_IP\n, [SESSIONB.AUTH] SESSION_AUTH\n, [PIN__PIN, ID ] PIN\nFROM EMP\nWHERE 1 = 1\n\n[~ P1 ^ IS_NOT_NULL ^ AND [P1] = [P1] ~]\n[~ P2 ^ IS_NULL ^ AND 2 = 2 ~]\n[~ P3 ^ Y ^ AND ''Y'' = [P3] ~]\n\n[[ SQLRUNNER_TEST_04 ]]\n\nAND ''FIN''=''FIN''\n','\n',char(10)),NULL);
INSERT INTO FW_SQL VALUES('SQLRUNNER_TEST_10','select count(*) from emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp, emp',2);
DROP TABLE FW_SRT; 
CREATE TABLE FW_SRT (
OPT PRIMARY KEY
, MODE
, KEY
, IV
);
INSERT INTO FW_SRT VALUES('S01','Aria_ECB_ZERO','E231C123B7512A8A9027E9EE99C0C684','');
INSERT INTO FW_SRT VALUES('S02','Aria_CBC_PKCS7','B426E1A441F6DBFC2B2D2412D0066D20','52A9A4CC4FB1EF00A72FF87583D44E5C');
INSERT INTO FW_SRT VALUES('S03','Aes_CBC_PKCS7','BF210BE9E2ED4620B442D5AF8D000E40','CF80492ACF3166C7CC039818619E4859');
INSERT INTO FW_SRT VALUES('SDB','Aria_CBC_PKCS7','B426E1A441F6DBFC2B2D2412D0066D20','52A9A4CC4FB1EF00A72FF87583D44E5C');
drop TABLE FW_VIEW ;
CREATE TABLE FW_VIEW (
KEY PRIMARY KEY
, JSP
, TMPL_JSP, TITLE);
INSERT INTO FW_VIEW VALUES('loginView','/WEB-INF/classes/com/code5/biz/login/jsp/loginView.jsp',NULL,NULL);
INSERT INTO FW_VIEW VALUES('fileDownload','/WEB-INF/classes/com/code5/fw/web/jsp/fileDownload.jsp',NULL,NULL);
INSERT INTO FW_VIEW VALUES('downloadFile','/WEB-INF/classes/com/code5/fw/web/jsp/downloadFile.jsp',NULL,NULL);
INSERT INTO FW_VIEW VALUES('emp00110','/WEB-INF/classes/com/code5/biz/emp/emp001/jsp/emp00110.jsp','/WEB-INF/classes/com/code5/biz/emp/jsp/empMain.jsp','EMP 조회');
INSERT INTO FW_VIEW VALUES('nullView','/WEB-INF/classes/com/code5/fw/web/jsp/nullView.jsp','','');
INSERT INTO FW_VIEW VALUES('errView','/WEB-INF/classes/com/code5/fw/web/jsp/errView.jsp','','');
CREATE TABLE BZ_ID (
ID PRIMARY KEY
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM
);
INSERT INTO BZ_ID VALUES('id_A0','424ab5a6448f7b6aca9cd65c361b672c3d853622bd29001ee15bc5c50bcfa169','A0',0,'');
INSERT INTO BZ_ID VALUES('id_U0','337c1456c9b72fd82583e974ac3885295373b1968210cfc0cb5418c554935f4f','U0','0','');
CREATE TABLE FW_FILE_DOWNLOAD (
REAL_FILE_NAME
, ID
, ST_DTM
, ED_DTM
);
CREATE TABLE FW_FILE_UPLOAD (
FILE_ID primary KEY
, SIZE
, NAME
, CONTENT_TYPE
, FILE_NAME
, FILE_URL
, RG_ID
, RG_DTM
);
drop table FW_UPLOAD_FILE;
CREATE TABLE FW_UPLOAD_FILE (
FILE_ID primary KEY
, SIZE
, CONTENT_TYPE
, FILE_NAME
, FILE_URL
, RG_ID
, RG_DTM
, DEL_Y
, DEL_ID
, DEL_DTM
);
drop table FW_DOWNLOAD_FILE;
CREATE TABLE FW_DOWNLOAD_FILE (
FILE_ID
, ID
, DTM
);
drop table FW_CONTROLLER;
CREATE TABLE FW_CONTROLLER(
  KEY,
  CLASS_NAME,
  METHOD_NAME);
INSERT INTO FW_CONTROLLER VALUES('login','com.code5.biz.login.Login','login');
INSERT INTO FW_CONTROLLER VALUES('loginView','com.code5.biz.login.Login','loginView');
INSERT INTO FW_CONTROLLER VALUES('filedownload','com.code5.fw.web.MasterControllerMultipart','fileDownload');
INSERT INTO FW_CONTROLLER VALUES('downloadfile','com.code5.fw.web.MasterControllerMultipart','downloadFile');
INSERT INTO FW_CONTROLLER VALUES('emp00110','com.code5.biz.emp.emp001.Emp001','emp00110');
INSERT INTO FW_CONTROLLER VALUES('emp00120','com.code5.biz.emp.emp001.Emp001','emp00120');
INSERT INTO FW_CONTROLLER VALUES('emp00210','com.code5.biz.emp.emp002.Emp002','emp00210');
INSERT INTO FW_CONTROLLER VALUES('emp00220','com.code5.biz.emp.emp002.Emp002','emp00220');
INSERT INTO FW_CONTROLLER VALUES('admin001','com.code5.fw.web.Admin','admin001');
