cd C:\public\sqlite
sqlite3 C:\public\sqlite\code5.db

DROP TABLE FW_CONTROLLER;

DROP TABLE FW_VIEW;

CREATE TABLE FW_CONTROLLER (
KEY PRIMARY KEY
, CLASS_NAME
, METHOD_NAME
);

CREATE TABLE FW_VIEW (
KEY PRIMARY KEY
, JSP
);



INSERT INTO FW_CONTROLLER VALUES ('emp00110','com.code5.biz.emp.Emp001','emp00110');
INSERT INTO FW_CONTROLLER VALUES ('emp00120','com.code5.biz.emp.Emp001','emp00120');

INSERT INTO FW_VIEW VALUES ('emp00110','/WEB-INF/classes/com/code5/biz/emp/jsp/emp00110.jsp');


INSERT INTO FW_CONTROLLER VALUES ('login','com.code5.biz.login.Login','login');
INSERT INTO FW_CONTROLLER VALUES ('loginView','com.code5.biz.login.Login','loginView');

INSERT INTO FW_VIEW VALUES ('loginView','/WEB-INF/classes/com/code5/biz/login/jsp/loginView.jsp');


DELETE FROM FW_SQL WHERE KEY IN ('MASTERCONTROLLERD_01','MASTERCONTROLLERD_02'); 

INSERT INTO FW_SQL VALUES (
'MASTERCONTROLLERD_01'
, 'SELECT
KEY
, CLASS_NAME
, METHOD_NAME
FROM FW_CONTROLLER
WHERE KEY = [KEY]'
);

INSERT INTO FW_SQL VALUES (
'MASTERCONTROLLERD_02'
, 'SELECT
KEY
, JSP
FROM FW_VIEW
WHERE KEY = [KEY]'
);

